name: Update servers.txt
permissions: write-all

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
#      with:
#        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    - name: Run Python script
      run: python main.py

    - name: Commit and push changes
      uses: devops-infra/action-commit-push@v1.0.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_message: "Update servers.txt"
#        amend: true
#        force_with_lease: true
#      uses: EndBug/add-and-commit@v7
#      with:
#        author_name: "GitHub Actions"
#        author_email: "actions@github.com"
#        message: "Update"
#        add: "."
#        pull: "NO-PULL"
#        push: true
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
